### PR TITLE
-Fixes table parameters not being updated

### PR DESCRIPTION
**Pull request by PavelBal**
-List of variable table parameters does not have the field "Path", so variable table parameters were never updated.

### CODE REVIEW

**Comment by Yuri05** [comment]
* Build failed
* Do we have tests for this?

**Comment by PavelBal** [comment]
- Probably because of https://github.com/Open-Systems-Pharmacology/R-Toolbox/issues/113
- We do have tests, but they always passed ;) So, I guess, we have to design new tests.

**Comment by Yuri05** [comment]
>So, I guess, we have to design new tests.

Yep. Can you add it please?

**Comment by PavelBal** [comment]
> > So, I guess, we have to design new tests.
> 
> Yep. Can you add it please?

Did it.

**Comment by Yuri05** [comment]
ok, after #114 is merged, we can also merge this PR

**Comment by msevestre** [comment]
@PavelBal @Yuri05 What issues are being fixed here?
Please referenced the issues being worked on in the commit message by # . Otherwise it's very hard to track

**Comment by PavelBal** [comment]
There was no open issue for this bug. I'll make sure to create corresponding issues in future.

**Pull request merged**
