### PR TITLE
Fixes #18, #35, #41, Enable running unit tests from command line; Change getParameter/getXXX behavior when nothing found.

### LINKED ISSUE #18: Typo in documentation of initParameter
The documentation states:

initializeIfFormula | Should the parameter be initialized if it contains a formula? ("never", "allways", "withWarning")

It must be "always" and not "allways".

### LINKED ISSUE #35: Run R Unit tests on CI
Apparently there are Unit tests in R!! Woot woot. But...we are not running them before creating the package which is not so great.

An awesome feature would be to be able to run those tests via command line from the CI Server. 
Right now we are performing quite a bunch of stuff to package the code into an R package etc.. 
Especially we have to install 
 * R
 * R Tools. 

Is there a way to run those unit tests ? A simple command line would be enough. 

The appveyor script could be updated to run all tests upon commit and would fail if one or more test is failing. 

Anyone?

### LINKED ISSUE #41: getParameter() stops when the given parameter is not found
The behavior of getParameter() (and also of getTableParameter()) is that it stops when the provided parameter is not found, interrupting the code. This is OK and should be managed by try-catch construct when the user searches for a parameter.

First problem:The try-catch hint should be placed to the documentation of the method - does R documentation has an extra block for the exceptions/errors the method can produce?

Second problem: No user probably knows of this behavior, because getParameter() ALWAYS returned something, even if the parameter is not in the simulation (or not for the specific type). In that case, the output was

```
$Value
numeric(0)

$Index
[1] 0
```

and everything happily proceeded with this output. Now that this is fixed and getParameter() behaves like it was supposed to behave (stopping when the parameter is not found), the users would be surprised to see their code "broken".

Third problem: Searching for all parameters, e.g., by `getParameter("*", list(Type="variable"), DCI_Info = myDCI)` can also cause errors. Instead, the method getParameterStatus should be used.

So this "new - old" behavior should be mentioned in the next release notes.

OR: whe change the behavior of getParameter/getTableParameter/getSpeciesInitialValue in that way that it ALWAYS will return a list with the columns "value" and "Index". If the given parameter is not found, the lenght of this list would be zero. Additionally, a warning message is to be displayed.

### PR DESCRIPTION
**Pull request by PavelBal**
- getParameter/getObserverFormula/getSpeciesInitialValue/getTableParameter returns an empty list when no parameter found (instead of stopping)
- Fixed getParameter failing to find a table parameter
- Adapted unit tests to the new behavior of getXXX()
- DoRUnitTesting.R can be called from CLI and returns an integer representing the number of errors.

Unit testing fails with 5 errors.

- Fixes #18 
- Fixes #35 
- Fixes #41

### CODE REVIEW

**Comment by msevestre** [comment]
@PavelBal Very neat. Thanks

>DoRUnitTesting.R can be called from CLI and returns an integer representing the number of errors.

Can you paste an example of how CLI call looks like?

A quick remark: Unless an issue is trivial such as #18 , let's try to solve only one issue per Pull Request. This makes it much easier to understand a code change in the long run.

**Comment by PavelBal** [comment]
> Can you paste an example of how CLI call looks like?

`C:\Program Files\R\R-3.4.3\bin\i386>Rscript "yourPath/OSP_R_Toolbox/tests/DoRUnitTesting.R" "yourPath/Toolbox/OSP_R_Toolbox/"`

Use Rscript to run an R-script from command line (be sure to call the x86-version of it!). The first argument is the path to the script you want to call, the second argument is the path to the directory of the R-Toolbox (with the subfolders "src" and "tests").

My naive thinking was that it would be enough when the called function returns the number of errors produced during the test. Now I have doubts, as I could not find how to assign the value of this "output" to a variable in Windows's cmd. So I am no sure, how to distinguish between some text output like warnings generated by some functions (which are just printed into the command line), and the actual output value of the called script.

**Comment by PavelBal** [comment]
To make it simple - the exit code is 0 if no errors were found, and 10 otherwise. 10 and not 1 or else because of the R-documentation:

> Some error status values are used by R itself. The default error handler for non-interactive use effectively calls q("no", 1, FALSE) and returns error status 1. Error status 2 is used for R ‘suicide’, that is a catastrophic failure, and other small numbers are used by specific ports for initialization failures. It is recommended that users choose statuses of 10 or more.

When providing the path to the toolbox-directory, use "/" instead of "\\", and append a "/" at the end of the path.

**Comment by msevestre** [comment]
@Yuri05 Someone needs to review that before it gets stale

**Comment by Yuri05** [comment]
>Someone needs to review that before it gets stale

In Progress

**Review by sfrechen — APPROVED** [review]

**Pull request merged**
