### PR TITLE
Update Unit tests

### PR DESCRIPTION
**Pull request by PavelBal**
-Minor unit test updates - correct checks for warnings.

### CODE REVIEW

**Comment by msevestre** [comment]
@Yuri05 Do not merge until we release 7.3

**Comment by msevestre** [comment]
@PavelBal Super hard to see what has changed here because your changes has over 7 commits that were already merged into the main branch.

Especially there is some code about steady state etc.. that has nothing to do with minor changes described above

I'd suggest to follow our git workflow and rebase you development branch before pushing a PR

in your case, the easiest way is to simply do the following
```
git pull upstream develop
git checkout -b udpate-unit-test 
git cherry-pick xxxxx where xxx is the commit hash with your fix.
```
Closing as this cannot be merged as is

**Comment by PavelBal** [comment]
Yes, I see I messed up this one (actually I messed it up in my fork). Will close this one and re-commit later.

**Comment by msevestre** [comment]
check the workflow out
https://github.com/Open-Systems-Pharmacology/Suite/blob/develop/GIT_WORKFLOW.md

**Pull request closed without merging**
